### ISSUE TITLE
Hardcoding of number of replicates per processor

### ISSUE THREAD

**Issue by tokami** [DLMtool/DLMtool#284]
Running `runMSE` in parallel requires more than 144 replicates to split the replicates equally among available processors. If the user chooses to run less than 144 replicates, the code only uses 4 processors even though blocking `ncpu` processors and also printing the incorrect message to the console: ```Running MSE in parallel on 'ncpu' processors``` 

```
    ncpu <- snowfall::sfCpus()
    nits <- ceiling(OM@nsim/48)
    
    itsim <- rep(48,nits)
    
    if (nits < ncpu) {
      if (nits < 4) {
        nits <- 4
        itsim <- rep(ceiling(OM@nsim/4), 4)
      } else{
        nits <- ncpu
        itsim <- rep(ceiling(OM@nsim/ncpu), ncpu)
      }
     
}
```
(lines 158 - 168 in `runMSE.r`).

Why don't you distribute the replicates to the specified number of processors equally and independently of `OM@nsim`?

Alternatively, it would be nice to be able to change this setting or at least get a correct message about the effectively used number of processors!

Thank you for your amazing work on this great package :)

**Comment by AdrianHordyk** [comment]
The main reason for doing this was to set a limit of at least 48 sims per core. Otherwise few total sims with a large number of cores can result in very few sims per core. This can lead to issues when parameters (e.g recruitment sigmaR, steepness, depletion) are re-sampled when the model has difficulty reaching the specified depletion (few sims = little variability to sample from).

This was a hack to fix that issue - hence the oversight in the incorrect message.  Thanks for pointing it out - will look into fixing it soon.

Also, with few total simulations (eg < few hundred) it is often the case that the overhead in setting up more cores with fewer sims is greater than the time lost in using fewer cores with more sims. Agree that an option to change the setting would be useful though

**Comment by quang-huynh** [comment]
As I work with model-based MPs, the parallel processing is beneficial even with few simulations, i.e. 100. These OMs will also be conditioned on `SRA_scope` so it shouldn't run into re-sampling issues.

A simple control argument can be used to hardwire the number of CPUs, e.g. `runMSE(control = ncpus = 12)` and override the current default behavior.

**Comment by AdrianHordyk** [comment]
Default in upcoming V6.0 will be:
 - if `setup()` has already been called, `OM@nsim` will be distributed over the initialized cores (ie `snowfall::sfCpus()`). This could result in very few sims per core, so something to be aware of.
- if `setup()` has not been called, parallel processing will be initialized with `floor(OM@nsim/48)` processors
